package org.olr.nonadmin

import org.olr.admin.User

class Contact {
    private static final long serialVersionUID = 1

//  Integer id // autogenerated
//  Integer version // autogenerated
    String subject
    String feedback
    Date dateCreated
    User owner  // not editable

    static constraints = {
        id generator: 'identity'  // added
        subject nullable: false, size: 4..32
        feedback sqlType: 'text', nullable: false, widget: 'textarea'
        owner nullable: false
    }


    @Override
    String toString() {
        return "${id}"
    }

}
