package org.olr.nonadmin
import org.olr.admin.User

class QuestionFile {
//  Integer id // autogenerated by db
//  Integer version - autogenerated integer
    String questionsJson  // very long json string
    boolean publik  // public to all users
    Date dateCreated  // auto filled
    Date lastUpdated  // auto filled

    static belongsTo = [owner: User]
    User owner

    static constraints = {
        id generator: 'identity'  // added
        questionsJson  sqlType: 'text', nullable:false, widget: 'textarea'
        owner nullable: false, editable: false  /* ignored by fields plugin */
    }

    @Override
    String toString() {
        return "${id}"
    }

}
